### ISSUE TITLE
Error messages at install

### ISSUE THREAD

**Issue by usctzen** [irahorecka/python-craigslist-meta#1]
Hi Ira,

Wanted to give your addon a spin and I got this at install

`(venv) C:\Users\mgpd\PycharmProjects\molivo>pip install python-craigslist-meta
Collecting python-craigslist-meta
  Downloading python-craigslist-meta-0.1.2.tar.gz (25 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mgpd\pycharmprojects\molivo\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mgpd\\AppData\\Local\\Temp\\pip-install-ben767ri\\python-craigslist-meta_9e7670eace6c41739
a311bc05bd71d6d\\setup.py'"'"'; __file__='"'"'C:\\Users\\mgpd\\AppData\\Local\\Temp\\pip-install-ben767ri\\python-craigslist-meta_9e7670eace6c41739a311bc05bd71d6d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=
f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mgpd\AppData\Local\Temp\pip-pip-egg-info-rg0y796p'
         cwd: C:\Users\mgpd\AppData\Local\Temp\pip-install-ben767ri\python-craigslist-meta_9e7670eace6c41739a311bc05bd71d6d\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mgpd\AppData\Local\Temp\pip-install-ben767ri\python-craigslist-meta_9e7670eace6c41739a311bc05bd71d6d\setup.py", line 26, in <module>
        long_description=open("README.rst").read(),
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1965: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ca/3e/f6f78b63f674bcc1316199a0c09704a18643ba915d5721d9023d69f42643/python-craigslist-meta-0.1.2.tar.gz#sha256=40c18a9a727981fc318df58780df810ad74cb8703a124cb9b2a4738454e78e4f
(from https://pypi.org/simple/python-craigslist-meta/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading python-craigslist-meta-0.1.1.tar.gz (24 kB)
Building wheels for collected packages: python-craigslist-meta
  Building wheel for python-craigslist-meta (setup.py) ... done
  Created wheel for python-craigslist-meta: filename=python_craigslist_meta-0.1.1-py3-none-any.whl size=23857 sha256=6d7c153db9e6958479b83192ddad71d383fec929d3767dda0c69973c739c6e00
  Stored in directory: c:\users\mgpd\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\45\2a\72\1da8aec745d3e3c2ff8511c57da9983dd4255dddde212e6147
Successfully built python-craigslist-meta
Installing collected packages: python-craigslist-meta
Successfully installed python-craigslist-meta-0.1.1

(venv) C:\Users\mgpd\PycharmProjects\molivo>
`

**Comment by irahorecka** [comment]
Hi @usctzen, thank you for the issue, I'll take a look at it. 
It appears that v0.1.1 was installed successfully while v0.1.2 failed?

**Comment by usctzen** [comment]
Yes. 0.1.1 is installed and 0.1.2 refuses to upgrade.

Le jeu. 25 févr. 2021 à 22:39, Ira Horecka <notifications@github.com> a
écrit :

**Comment by irahorecka** [comment]
@usctzen ok the bug should be fixed, the latest version is 0.1.4 (`pip install python-craigslist-meta==0.1.4`). Please let me know if there are follow-up issues or concerns.

**Comment by usctzen** [comment]
Installed the 0.1.4 package this morning and it went fine. Get ready for
some questions and wishes.

Thanks, Ira.

Le ven. 26 févr. 2021 à 04:57, Ira Horecka <notifications@github.com> a
écrit :
